version: '3.8'

services:
  mongodb:
    build: 
     context: .
     dockerfile: Dockerfile.mongodb
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: itaminul2
      MONGO_INITDB_ROOT_PASSWORD: itaminul2
  shadow-db:
    image: mongo:4.4
    container_name: shadow-db
    restart: always
    ports:
      - '27018:27017'

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://itaminul2:itaminul2@localhost:27017/erp-api?retryWrites=true&w=majority&authSource=admin
      # MONGO_URI: mongodb+srv://itaminul2:itaminul2@erp-api.8fcd1ip.mongodb.net/
      # SHADOW_DB_URI: mongodb+srv://itaminul2:itaminul2@shadow-erp-api.8fcd1ip.mongodb.net/

  prisma:
    build:
      context: .
      dockerfile: Dockerfile.prisma
    container_name: prisma
    restart: always
    depends_on:
      - mongodb
